# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - errorlint
  exclusions:
    paths:
      - .dagger
      - vendor
      - tmp
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - noctx
