version: "3"

vars:
  APP_NAME: therefore
  DEV_IMAGE: "{{.APP_NAME}}:dev"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  dev:
    desc: Start development environment with hot-reload
    cmds:
      - docker compose up --build

  dev-stop:
    desc: Stop development environment
    cmds:
      - docker compose down

  dev-logs:
    desc: View development logs
    cmds:
      - docker compose logs -f

  dev-shell:
    desc: Open shell in dev container
    cmds:
      - docker compose exec dev sh

  build:
    desc: Build production container via Dagger
    cmds:
      - defer: rm ./{{.APP_NAME}}-local.tar
      - dagger -m .dagger call release --source=. export --path ./{{.APP_NAME}}-local.tar
      - |
        id=$(docker load -i ./{{.APP_NAME}}-local.tar | sed -n 's/^Loaded image.*: //p')
        docker tag $id {{.APP_NAME}}:local

  build-frontend:
    desc: Build frontend assets via Dagger
    cmds:
      - dagger -m .dagger call build-frontend --source=. export --path=./internal/static/dist

  test:
    desc: Run Go tests via Dagger
    cmds:
      - dagger -m .dagger call test --source=.

  lint:
    desc: Run Go linter via Dagger
    cmds:
      - dagger -m .dagger call lint --source=.

  lint-frontend:
    desc: Run frontend ESLint via Dagger
    cmds:
      - dagger -m .dagger call lint-frontend --source=.

  typecheck:
    desc: Run TypeScript type-check via Dagger
    cmds:
      - dagger -m .dagger call typecheck --source=.

  test-frontend:
    desc: Run frontend Vitest tests via Dagger
    cmds:
      - dagger -m .dagger call test-frontend --source=.

  check:
    desc: Run all checks (lint, typecheck, test)
    cmds:
      - task: lint
      - task: lint-frontend
      - task: typecheck
      - task: test
      - task: test-frontend

  fmt:
    desc: Format Go code via Dagger
    cmds:
      - dagger -m .dagger call fmt --source=. export --path=.

  fmt-frontend:
    desc: Format frontend code via Dagger
    cmds:
      - dagger -m .dagger call fmt-frontend --source=. export --path=.

  templ:
    desc: Generate templ files via Dagger
    cmds:
      - dagger -m .dagger call templ-generate --source=. export --path=.

  templ-fmt:
    desc: Format templ files via Dagger
    cmds:
      - dagger -m .dagger call templ-fmt --source=. export --path=.

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf ./tmp ./bin
      - rm -rf ./frontend/node_modules
      - rm -rf ./internal/static/dist

  clean-docker:
    desc: Remove Docker volumes and images
    cmds:
      - docker compose down -v
      - docker rmi {{.DEV_IMAGE}} 2>/dev/null || true
