name: ci

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    env:
      DAGGER_NO_NAG: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Run Check
        uses: dagger/dagger-for-github@27b130bf0f79a7f6fbbbe0fbca6760dc9bb40a77 # v8.4.1
        with:
          version: "latest"
          verb: call
          module: .dagger
          args: check --source=.

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DAGGER_NO_NAG: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Run Build
        uses: dagger/dagger-for-github@27b130bf0f79a7f6fbbbe0fbca6760dc9bb40a77 # v8.4.1
        with:
          version: "latest"
          verb: call
          module: .dagger
          args: build --source=.
