name: renovate
on:
  schedule:
    - cron: "30 9 * * 2,5"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@6d859fc95779be83a0335ca704879b47e5d79641 # v46.1.16
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          LOG_LEVEL: "info"
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
